name: Subir APK a App Center
 
on:
  push:
    branches: [ main ]
 
jobs:
  build-and-release:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2
 
      - name: Configurar Gradle
        uses: gradle/setup-gradle@v3
        with:
         gradle-version: '8.0'
 
      - name: Construir APK
        run: ./gradlew assembleRelease
 
      - name: Distribuir APK a Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.0
        with:
          name: Test.apk
          appId: ${{ secrets.FIREBASE_APP_ID_1:115198699492:android:0998dc6499a8560a4ac9f1 }}
          token: ${{ secrets.FIREBASE_TOKEN_BCpW84w6zfJdwnf4DhzSjwk-kDr6lgmuY6OnO7_Hc7Pu_EIDtzUgofnBpmQCOJ49vsd09gngLdhQUftbFLJUYUI }}
          groups: ${{ secrets.FIREBASE_DISTRIBUTION_GROUPS_test }}
          path: app/build/outputs/apk/release/app-release.apk
